services:
  db:
    image: postgres:15
    container_name: vete-db
    environment:
      POSTGRES_USER: admin-vet
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: veterinaria_db
    ports:
      - "5432:5432"
    volumes:
      - vete-data:/var/lib/postgresql/data

volumes:
  vete-data: